### ISSUE TITLE
not working in ardour6

### ISSUE THREAD

**Issue by michal-cab** [jeremysalwen/TalentedHack#8] opened 2022-02-08 13:13 UTC
after compiling latest version and trying to load plugin in ardour it says:

Port 0 ('MIDI Out') has no known data type
Port 1 ('MIDI In') has no known data type

**Comment by AS383** [comment] 2022-02-08 14:03
Duplicate of issue #7

**Comment by jeremysalwen** [comment] 2022-02-12 17:39
#7 is fixed, so I think it should work in ardour now.  Please reopen if it doesn't.

**Closed by jeremysalwen** 2022-02-12 17:39 UTC
